# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - cp codecoq/html/toc.html codecoq/html/index.html
  - mkdir .public
  - cp codecoq/html/* -r .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master